site_name: "DataTable2"

theme:
  name: "material"
  favicon: 'images/favicon.ico'
  logo: 'images/logo.svg'

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - DataTable2: datatable2.md
  - DataColumn2: datacolumn2.md
  - DataRow2: datarow2.md